### ISSUE TITLE
[bug] something happend in components.py

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/Yggdrasil#87]
Reçu sur stderr:
Traceback (most recent call last):
  File "builder.py", line 26, in 
    dic = get_context()
  File "/home/docker/sandboxio.py", line 17, in get_context
    Component.sync_context(context)
  File "/home/docker/components.py", line 120, in sync_context
    context[k] = Component.deserialize(v, v)
  File "/home/docker/components.py", line 95, in deserialize
    return getattr(module, decorator)(**data)
AttributeError: module 'custommatchlist' has no attribute 'CustomMatchList'

**Comment by mciissee** [comment]
This is not a bug with the components framework. The bug come from the exercise you use **matchlist_csv** .

You use the code :
```
match.decorator = CustomMatchList
```

But there is no python file named **custommatchlist** containing the class **CustomMatchList**.
the python file must be the lowercase version of the decorator name.

Another remarks I suggest you to wait before using this feature of the components since I will change it soon.

**Comment by nimdanor** [comment]
thanks
